import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import React from "react";

import "./globals.css";
import Header from "@/components/common/Header";

const arimo = Arimo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-arimo"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={arimo.variable}>
        <Header />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
